/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package ch.zhaw.pm2.amongdigits;

import javafx.application.Application;

/** The main entry point for the application. */
public class App {

  /**
   * The main method that launches the application.
   *
   * @param args The command line arguments.
   */
  public static void main(String[] args) {
    Application.launch(SudokuGui.class, args);
  }
}
